name: "Selenium"
description: "Selenium Tests"
inputs:
  SeleniumRoot:
    description: 'Selenium Root Folder'
    required: yes
runs:
  using: "composite"
  steps: 
  - name: Install dependencies
    run: |
      cd ${{ inputs.SeleniumRoot }}
      ./Install-ChromeDriver.ps1
    shell: pwsh
