name: "Selenium"
description: "Selenium Tests"
inputs:
  SeleniumRoot:
    description: 'Selenium Root Folder'
    required: yes
runs:
  using: "composite"
  steps: 
  - name: Install dependencies
    run: |
      get-childitem -path ..\..\..\
      #$path = ..\..\..\..\Selenium\Install-ChromeDriver.ps1
      #Invoke-Command -Path $path
    shell: pwsh
