name: "Selenium"
description: "Selenium Tests"
runs:
  using: "composite"
  steps: 
  - name: Install dependencies
    run: |
      $GITHUB_WORKSPACE\Selenium\Install-ChromeDriver.ps1
    shell: pwsh
