# Continuous Integration workflow

name: Continuous Integration PR Non Production

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: [ develop ]
    paths:
      - Source/*
      - .github/workflows/app.ci.non_prod.yml
      - .github/workflows/CI/*
      - .github/workflows/Compile/*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  ContinuousIntegration_Testing:
      name: "AutomatedTests"
      runs-on: ubuntu-latest

      steps:
        - name: "Checkout"
          uses: actions/checkout@master
        - name: "Lint"
          uses: ./.github/workflows/CI/linters
        - name: "UnitTests"
          uses: ./.github/workflows/CI/unit
        - name: "IntegrationTests"
          uses: ./.github/workflows/CI/integration

  ContinuousIntegration_Compile:
      name: "Compile"
      runs-on: ubuntu-latest
      needs: ContinuousIntegration_Testing
      steps:
        - name: "Checkout"
          uses: actions/checkout@master
        - name: "Compile"
          uses: ./.github/workflows/Compile
