# Continuous Integration workflow

name: Continuous Integration PR Non Production

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: [ develop, master ]
    paths:
      - Source/*
      - Source/Tests/Selenium/SeleniumTests/SeleniumTests/*
      - .github/workflows/app.ci.pull_request.yml

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  ContinuousIntegration_Testing:
    name: "CITests"
    runs-on: windows-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v2
      with: 
        ref: 'develop'
    - name: Setup .NET 3.1.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: "UnitTests"
      uses: ./.github/workflows/CI/unit
    - name: "SeleniumTests"
      uses: ./.github/workflows/CI/Selenium
      with:
        SeleniumRoot: "$GITHUB_WORKSPACE/Source/Tests/Selenium/"
