# Continuous Deployment workflow

name: Continuous Deployment Non Production

# Controls when the action will run. 
on:
  workflow_run:
    workflows: ["Continuous Integration Non Production"]
    branches: [develop]
    types: 
      - completed
      - requested

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  ContinuousDeployment_Compile:
      name: "Compile"
      runs-on: ubuntu-latest
      steps:
        - name: "Checkout"
          uses: actions/checkout@master
        - name: "Compile"
          uses: ./.github/workflows/Compile

  ContinuousDeployment_Publish:
      name: "Publish"
      runs-on: ubuntu-latest
      needs: ContinuousDeployment_Compile
      steps:
        - name: "Checkout"
          uses: actions/checkout@master
        - name: "Publish"
          uses: ./.github/workflows/Publish/non_prod

  ContinuousDeployment_Deploy:
      name: "Deploy"
      runs-on: ubuntu-latest
      needs: ContinuousDeployment_Publish
      steps:
        - name: "Checkout"
          uses: actions/checkout@master
        - name: "Deploy"
          uses: ./.github/workflows/Deploy/non_prod
