# Continuous Integration workflow

name: CICD Non Production

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ develop ]
    paths:
      - Source/*
      - .github/workflows/app.cicd.non_prod.yml
      - .github/workflows/CI/*
      - .github/workflows/Compile/*
      - .github/workflows/Publish/non_prod/*
      - .github/workflows/Deploy/non_prod/*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  ContinuousIntegration_Testing:
      name: "AutomatedTests"
      runs-on: ubuntu-latest

      steps:
        - name: "Checkout"
          uses: actions/checkout@v2
          with: 
            ref: 'develop'
        - name: "Lint"
          uses: ./.github/workflows/CI/linters
        - name: "UnitTests"
          uses: ./.github/workflows/CI/unit
        - name: "IntegrationTests"
          uses: ./.github/workflows/CI/integration

  ContinuousIntegration_Compile:
      name: "Compile"
      runs-on: ubuntu-latest
      needs: ContinuousIntegration_Testing
      steps:
        - name: "Checkout"
          uses: actions/checkout@v2
          with: 
            ref: 'develop'
        - name: "Compile"
          uses: ./.github/workflows/Compile

  ContinuousDeployment_Publish:
      name: "Publish"
      runs-on: ubuntu-latest
      needs: ContinuousIntegration_Compile
      steps:
        - name: "Checkout"
          uses: actions/checkout@v2
          with: 
            ref: 'develop'
        - name: dotnet build and publish
          run: |
            dotnet restore
            dotnet build --configuration Release
            dotnet publish -c Release -o './Source/Contoso.Expenses.Web' 

  ContinuousDeployment_Deploy:
      name: "Deploy"
      runs-on: ubuntu-latest
      environment: "Non-Production"
      needs: ContinuousDeployment_Publish
      steps:
        - name: "Checkout"
          uses: actions/checkout@v2
          with: 
            ref: 'develop'
        - name: "DeployWebToNonProduction"
          uses: azure/webapps-deploy@v2
          with: 
            app-name: "expenseweb" # Replace with your app name
            publish-profile: ${{ secrets.INTERNAL_EXPENSE_APP_PUBLISH_PROFILE_WEB }} # Define secret variable in repository settings as per action documentation
            package: './Source/Contoso.Expenses.Web'
        - name: "DeployAPIToNonProduction"
          uses: azure/webapps-deploy@v2
          with: 
            app-name: "expenseapi" # Replace with your app name
            publish-profile: ${{ secrets.INTERNAL_EXPENSE_APP_PUBLISH_PROFILE_API }} # Define secret variable in repository settings as per action documentation
            package: './Source/Contoso.Expenses.API'

