# Continuous Integration workflow

name: CICD Non Production

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ develop ]
    paths:
      - Source/*
      - .github/workflows/app.cicd.non_prod.yml
      - .github/workflows/CI/*
      - .github/workflows/Compile/*
      - .github/workflows/Publish/non_prod/*
      - .github/workflows/Deploy/non_prod/*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  ContinuousIntegration_Testing:
    name: "AutomatedTests"
    runs-on: windows-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v2
      with: 
        ref: 'develop'
    - name: "UnitTests"
      uses: ./.github/workflows/CI/unit
    - name: "SeleniumTests"
      uses: ./.github/workflows/CI/Selenium
      with:
        SeleniumRoot: "$GITHUB_WORKSPACE/Source/Tests/Selenium/"

  ContinuousDeployment_Deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    environment: "Non-Production"
    needs: ContinuousIntegration_Testing
    steps:
    - name: "Checkout"
      uses: actions/checkout@v2
      with: 
        ref: 'develop'
    - name: "DeployWebToNonProduction"
      uses: azure/webapps-deploy@v2
      with: 
        app-name: "expenseweb" # Replace with your app name
        publish-profile: ${{ secrets.INTERNAL_EXPENSE_APP_PUBLISH_PROFILE_WEB }} # Define secret variable in repository settings as per action documentation
        package: './Source/Contoso.Expenses.Web'
    - name: "DeployAPIToNonProduction"
      uses: azure/webapps-deploy@v2
      with: 
        app-name: "expenseapi" # Replace with your app name
        publish-profile: ${{ secrets.INTERNAL_EXPENSE_APP_PUBLISH_PROFILE_API }} # Define secret variable in repository settings as per action documentation
        package: './Source/Contoso.Expenses.API'
