# Continuous Integration workflow

name: CICD Non Production

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ develop ]
    paths:
      - Source/*
      - .github/workflows/app.ci.non_prod.yml
      - .github/workflows/app.cd.non_prod.yml
      - .github/workflows/CI/*
      - .github/workflows/Compile/*
      - .github/workflows/Publish/*
      - .github/workflows/Deploy/*


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  ContinuousIntegration_Testing:
      name: "AutomatedTests"
      runs-on: ubuntu-latest

      steps:
        - name: "Checkout"
          uses: actions/checkout@v2
          with: 
            ref: 'develop'
        - name: "Lint"
          uses: ./.github/workflows/CI/linters
        - name: "UnitTests"
          uses: ./.github/workflows/CI/unit
        - name: "IntegrationTests"
          uses: ./.github/workflows/CI/integration

  ContinuousIntegration_Compile:
      name: "Compile"
      runs-on: ubuntu-latest
      needs: ContinuousIntegration_Testing
      steps:
        - name: "Checkout"
          uses: actions/checkout@v2
          with: 
            ref: 'develop'
        - name: "Compile"
          uses: ./.github/workflows/Compile

  ContinuousDeployment_Publish:
      name: "Publish"
      runs-on: ubuntu-latest
      needs: ContinuousIntegration_Compile
      steps:
        - name: "Checkout"
          uses: actions/checkout@v2
          with: 
            ref: 'develop'
        - name: "Publish"
          uses: ./.github/workflows/Publish/non_prod

  ContinuousDeployment_Deploy:
      name: "Deploy"
      runs-on: ubuntu-latest
      environment: "Non-Production"
      needs: ContinuousDeployment_Publish
      steps:
        - name: "Checkout"
          uses: actions/checkout@v2
          with: 
            ref: 'develop'
        - name: "Deploy"
          uses: ./.github/workflows/Deploy/non_prod
