# Continuous Deployment workflow

name: Continuous Deployment Non Production

# Controls when the action will run. 
on:
  workflow_run:
    workflows: 
      - "Continuous Integration Non Production"
    types: 
      - completed

  workflow_dispatch:

jobs:
  ContinuousDeployment_Compile:
      name: "Compile"
      runs-on: ubuntu-latest
      steps:
        - name: "Checkout"
          uses: actions/checkout@v2
          with: 
            ref: 'develop'
        - name: "Compile"
          uses: ./.github/workflows/Compile

  ContinuousDeployment_Publish:
      name: "Publish"
      runs-on: ubuntu-latest
      needs: ContinuousDeployment_Compile
      steps:
        - name: "Checkout"
          uses: actions/checkout@v2
          with: 
            ref: 'develop'
        - name: "Publish"
          uses: ./.github/workflows/Publish/non_prod

  ContinuousDeployment_Deploy:
      name: "Deploy"
      runs-on: ubuntu-latest
      environment: "Non-Production"
      needs: ContinuousDeployment_Publish
      steps:
        - name: "Checkout"
          uses: actions/checkout@v2
          with: 
            ref: 'develop'
        - name: "Deploy"
          uses: ./.github/workflows/Deploy/non_prod
